version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATASOURCE: "jdbc:mysql://mysql:3306/blogdb"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    networks:
      - blog-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  backend:
    image: ghcr.io/wanjabachmann/blog-backend-eventhub:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - blog-nw
    env_file:
      - .\blog-backend\.env
networks:
  blog-nw:
